name: codebuild
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
    TARGET_ROLE_ARN: "arn:aws:iam::925935005908:role/cross-account-codebuild"
    TARGET_AWS_REGION: "us-east-1"

jobs:
  build:
    runs-on: 
      -  codebuild-ghActions-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Run shell commands
        run: |
          echo "Assuming role in Account B..."
          pip install awscli
          echo "Deploying to Account B..." > test.txt
          aws s3 cp test.txt s3://tcw-thecloudworld-codebuild --recursive
