name: codebuild
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: 
      -  codebuild-ghActions-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Run shell commands
        run: |
          echo "Assuming role in Account B..."
          touch test.txt
          echo "Deploying to Account B..." > test.txt
          aws s3 cp test.txt s3://tcw-thecloudworld-codebuild --recursive
