name: codebuild
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: 
      -  codebuild-ghActions-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - name: Run shell commands
        run: |
          echo "Assuming role in Account B..."
          ls -la
          aws s3 ls s3://tcw-gh-actions-artifact
